GET http://localhost:3000/recipes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTGVvIiwiaWF0IjoxNjU5NDU5ODAyLCJleHAiOjE2NTk0NTk4MTd9.RWjraajJg1mO7twiEoiWDW3lvJaayPo0vJKsCBF_nAg

###

GET http://localhost:3000/ingredients/

###

POST http://localhost:4000/login/
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###

post http://localhost:4000/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiVGVzdCIsImlhdCI6MTY1OTY0MzkxMiwiZXhwIjoxNjU5NjQ0ODEyfQ.16niVzC0BYABAU77V0caOlHEh3GxImZwwZXDnvRGXIs

###

POST http://localhost:4000/token/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTGVvIiwiaWF0IjoxNjU5NTI3MDM5fQ.DsuAuZ2vec_uxTXVWLdwgp4AAuUVx8Tsk0x6haRuvXk"
}

###

GET http://localhost:4000/testtoken/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTGVvIiwiaWF0IjoxNjU5NTI3MTgyLCJleHAiOjE2NTk1MjcxOTd9.9sqqTYKnn01fzf60TrSs_9qAUHSDjDmr_OYTeylnm5I

###

get http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTGVvIiwiaWF0IjoxNjU5NjMyMTMwLCJleHAiOjE2NTk2MzMwMzB9.kEa2D357LeaPKPg3V3IfLEj0y1k6gs8k1NTg5zLrww4

###

post http://localhost:4000/login/
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###

patch http://localhost:3000/recipe/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTGVvIiwiaWF0IjoxNjU5NTI3MTgyLCJleHAiOjE2NTk1MjcxOTd9.9sqqTYKnn01fzf60TrSs_9qAUHSDjDmr_OYTeylnm5I
Content-Type: application/json

{
    "RecipeId": 1,
    "RecipeOwner": "test"
}